spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:woolog
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
    open-in-view: false

  messages:
    basename: validation
    encoding: UTF-8

  data:
    web:
      pageable:
        page-parameter: true

jwt:
  secret-key: dGhpcyBpcyBteSBwZXJzb25hbCBwcm9qZWN0IHNlY3JldGtleQ==
  access-expiration-time: 3600
  refresh-expiration-time: 86400
  issuer: woolog
